### ISSUE TITLE
Problem with /dis p name

### ISSUE THREAD

**Issue by ghost** [robingrether/iDisguise#1]
Not showing player whose character is being used as /dis

On the /tab

**Comment by luisagrether** [comment]
Can you please give a more detailed and understandable description of the issue?

**Comment by ghost** [comment]
When you try do /dis p nameofplayer that person is no longer to be seen in Tab.

Even after /undis

**Comment by luisagrether** [comment]
I found the problem and I'm currently trying to fix it.

**Comment by ghost** [comment]
Sounds good
