### ISSUE TITLE
iDisguise 5.6.4-SNAPSHOT #16 and iDisguiseWG v1.1

### ISSUE THREAD

**Issue by Fiks75** [robingrether/iDisguise#14]
Spigot 1.12. iDisguise 5.6.4-SNAPSHOT #16 does not work with iDisguiseWG v1.1

10.08 04:51:21 [Server] ERROR Could not pass event PlayerMoveEvent to iDisguiseWG v1.1
10.08 04:51:21 [Server] INFO org.bukkit.event.EventException: null
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:647) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
10.08 04:51:21 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
10.08 04:51:21 [Server] INFO Caused by: java.lang.NoSuchMethodError: de.robingrether.idisguise.management.DisguiseManager.getInstance()Lde/robingrether/idisguise/management/DisguiseManager;
10.08 04:51:21 [Server] INFO at de.robingrether.idisguise.worldguard.EventListener.onPlayerMove(EventListener.java:33) ~[?:?]
10.08 04:51:21 [Server] INFO at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source) ~[?:?]
10.08 04:51:21 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
10.08 04:51:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO ... 15 more
10.08 04:51:21 [Server] ERROR Could not pass event PlayerMoveEvent to iDisguiseWG v1.1
10.08 04:51:21 [Server] INFO org.bukkit.event.EventException: null
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:647) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [survival.jar:git-Spigot-596221b-9a1fc1e]
10.08 04:51:21 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [survival.jar:git-Spigot-596221b-9a1fc1e]

Please fix it.

**Comment by luisagrether** [comment]
I already know about this problem. There will be an update for iDisguiseWG. Until then you can use the latest snapshot which you can download here: http://repo.robingrether.de/de/robingrether/idisguise/idisguise-wg/1.2-SNAPSHOT/

**Comment by luisagrether** [comment]
You may now update to the latest versions:
[**iDisguise** 5.6.4](https://www.spigotmc.org/resources/idisguise.5509/)
[**iDisguiseWG** 1.2](https://www.spigotmc.org/resources/idisguisewg.31156/)
