### ISSUE TITLE
[Feature Request] Viewable disguises 

### ISSUE THREAD

**Issue by Cobwebster** [robingrether/iDisguise#16]
Would it be possible to implement a system which lets you see what you're disguised as? Basically I use this plugin as a dependency to hide and seek, would be a lot better if you could actually see your disguised block. (basically what lib disguise does) 

We'd prefer to use iDisguise because of its feature which auto locks you as a block so it looks more realistic.

**Comment by luisagrether** [comment]
Well, to date my answer to this request has always been:

> The actual reason why this feature is not part of this plugin (and will never be) is that I personally think this feature is useless. To me Minecraft is a 1st person view game, I think playing Minecraft in 3rd person mode is plainly bad. In addition to this, implementing such a functionality would mean plenty hours of unpaid and unwanted work to me, which I'm not in the mood for. And finally: this feature is quite buggy and does not look particularly good as it is done with Libs Disguises (simply because Minecraft is not made to enable such things).
> 
> If you're opinion on this issue is different, I can fully understand that you rather like to use Libs Disguises on your server. :)

Fortunately, I think I've changed my mind about this lately :)
However, I can't give you an ETA when this enhancement might be available, since I started studying physics in October which takes up most of my free time :D

**Comment by luisagrether** [comment]
I've finally introduced this feature into the plugin. However, for now it works for player disguises only:

[iDisguise 5.7.4-SNAPSHOT #12](http://repo.robingrether.de/de/robingrether/idisguise/idisguise-full/5.7.4-SNAPSHOT/idisguise-full-5.7.4-20180705.205433-12.jar)

(If you disguise as a mob/object you will see the correspondent [MHF skin](https://minecraft.gamepedia.com/Mob_head#Mojang_skins) if one is available.)

**Comment by luisagrether** [comment]
I close this thread now that the feature is published.
