### ISSUE TITLE
Player Baby

### ISSUE THREAD

**Issue by HeberonYT** [robingrether/iDisguise#17]
Hello!
Thanks for your wonderful plugin.
I have a question that I have not solved, I need that the people in my server have the appearance of baby players, with their same skin and name but in small, is it possible to do this with your plugin?

**Comment by luisagrether** [comment]
I'm sorry. This is not possible with iDisguise.

Minecraft does not feature _baby_ players (or any general way of scaling entities), therefore you cannot have baby players without any sort of client-side modification.

**Comment by HeberonYT** [comment]
Ok, I appreciate your response.
regards
