### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AmazedMender16** [robingrether/iDisguise#19]
After one of the latest update my server is having huge amount of memory issues! 

Plugin that got updated was idisguise.

class de.robingrether.idisguise.management.util.EntityIdList @ ------
Shallow Size: 8 B Retained Size: 5.6 GB

class de.robingrether.idisguise.management.util.EntityIdList @ ------
Shallow Size: 8 B Retained Size: 3.1 GB

**Comment by luisagrether** [comment]
I will do my best to fix this issue as soon as possible.

By the way, I'm sorry for this inconvenient memory issue. My problem is that I only have a very small server available to test my plugin... so issues like this one are very hard to find....

**Comment by colinrgodsey** [comment]
also ran into this, trying v1.3.1 again to see if that fixes it

**Comment by luisagrether** [comment]
[iDisguise 5.7.4-SNAPSHOT #1](http://repo.robingrether.de/de/robingrether/idisguise/idisguise-full/5.7.4-SNAPSHOT/idisguise-full-5.7.4-20180616.094812-1.jar) should fix this issue.

**Comment by Zenya4** [comment]
I have this issue, too. The server started lagging *HARD* after I gave permissions for /d to everyone. Here is my heapdump. 8GB server running out of memory in just 4 hours! 

![unknown](https://user-images.githubusercontent.com/15248687/43041635-e2bf8c70-8d98-11e8-8330-3616091d4531.png)
![unknown 1](https://user-images.githubusercontent.com/15248687/43041636-e4b8c3fc-8d98-11e8-8a41-673935575a57.png)

I'll test out the snapshot for now. Thank you very much for fixing it!
