### ISSUE TITLE
maven repo?

### ISSUE THREAD

**Issue by xaoseric** [robingrether/iDisguise#2]
Hi,
Would you happen to have a maven repo for the plugin? If not, would you mind if I configured maven for the project?

**Comment by luisagrether** [comment]
About one year ago when I started using Git, I also tried to understand the advantages and use of build management tools like maven or gradle. But I finally stayed with basic Git because I don't see any gain from using something else. And also, I don't have the time to learn and understand how maven actually works. So I will not use maven for this project in the future.

**Comment by egg82** [comment]
I'm going to throw my two cents in as a plugin developer. I totally get it, I didn't understand why everyone was using Maven either. However, here's some points:

1. It makes it easier to build, shading in dependencies automatically
2. More importantly, it makes it easier for other developers using your plugin as a library or hook to use and get updates.

Here's an example:
I have a plugin called HatMeEnhanced which relies on LightAPI. LightAPI doesn't use Maven, and that requires me to keep on top of its updates, download it when there is one, create a "fake" maven project for it, and finally import it into the project and push an update.
I have another plugin called TrollCommands++ which relies on LibsDisguises. I still have to watch for updates, but when one comes along I simply change the number in my pom.xml and re-compile. Done.

I'd like to rely on this plugin as an optional alternative to LibsDisguises for server owner preferences, but I'm hesitant to as it would be a huge pain in my butt to constantly keep on top of the updates pushed out in the manner described above. I (and other devs, I'm sure) would like to simply change a number and be done with it.

An edit: I would like to re-open this issue and try for Maven support if you'd be up for it. Thank you for your time.

**Comment by luisagrether** [comment]
I'm working on it now.

**Comment by luisagrether** [comment]
For now, iDisguise is available like this:
````
<repositories>
  <repository>
    <id>robingrether-repo</id>
    <url>http://repo.robingrether.de/</url>
  </repository>
</repositories>

<dependencies>
  <dependency>
    <groupId>de.robingrether.idisguise</groupId>
    <artifactId>idisguise-core</artifactId>
    <version>5.6.1</version>
    <scope>provided</scope>
  </dependency>
</dependencies>
````

But I'm likely to make some more changes.

**Comment by egg82** [comment]
This makes it much easier to use your library, thank you very much! Your work is appreciated.

**Comment by luisagrether** [comment]
I finally finished configuring maven and pushed all the changes to this repository as well.

You should maybe refresh your dependencies, since I have been experimenting a bit while keeping the version number the same.

**Comment by egg82** [comment]
Excellent! Will give me an excuse to push out some minor changes of my own anyway.

**Comment by KateHutch** [comment]
Ty for the maven repo! Makes this April Fools plugin way easier! :+1:
