### ISSUE TITLE
Erasing the plugin will automatically Undisguise everyone ?

### ISSUE THREAD

**Issue by Nextshot** [robingrether/iDisguise#20]
No description necessary at all, the question is on the title

**Comment by luisagrether** [comment]
I don't see the point of this question...

I mean it is obvious that a plugin stops working if you uninstall it....

**Comment by Nextshot** [comment]
''There are naive questions, tedious questions, ill-phrased questions, questions put after inadequate self-criticism. But every question is a cry to understand the world. There is no such thing as a dumb question'' (At my case, ''''''Obvious question''''''')

I asked this because I wanted to erase the plugin without further contact with it, I asked because it may have edited something that I dont know, files outside of its own 'Plugin folder'.
You could have simply said the binary answer 'Yes' or 'No', as I dont know which answer it would be, I asked it here.
(For you it may sound like a question without a point, but for me there was a point, just like when you dont understand such a process and you ask 'How this works' and then learns)
As you extended your answer unnecessarily I did extend mine too, so, as me, you could learn something too. 
Thanks for the help... I guess...

**Comment by luisagrether** [comment]
To me this request sounded like a bug report at first glance.... In this case the question would be senseless.

Now I understand... nope, you're right. iDisguise does not leave any unwanted data. If you delete the plugin jar file and data folder, everything will behave as if you had never installed it :)

**Comment by Nextshot** [comment]
I asked this here because there is a button named 'Ask questions' at your mod page at spigot and the button redirects to github so I tought 'why not ?' Anyway, thank you.
Btw Iam not a lot familiar with Github, If I knew how I would have labelled the 'issue' as a question myself so It wouldnt be confused with a bug, kinda my fault this misunderstanding too :)
