### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by JPVortex225** [robingrether/iDisguise#22]
Hello, this is a quick question but, when is this plugin going to be updated to 1.13/1.13.1?? Thanks!

**Comment by luisagrether** [comment]
The latest snapshots support 1.13.1.
https://www.robingrether.de/idisguise/

At the moment, support for 1.13.1 is in the final testing stage. Thus you can expect an official update to be available by the end of this week.

**Comment by JPVortex225** [comment]
Awesome! Thank you :)

**Comment by luisagrether** [comment]
I'm very sorry. Unfortunately, I was too busy to finish testing the latest snapshot against 1.8.8, 1.9.4, 1.10, 1.11, 1.12 and 1.13.1.

Therefore I must delay the release of the new iDisguise update.

The latest snapshot should run 99% bug-free on Minecraft 1.13.1. So you can use that until the official update is finished.

**Comment by JPVortex225** [comment]
That’s fine and yeah the latest snapshots work great!

**Comment by luisagrether** [comment]
iDisguise 5.8.1 (including 1.13.1 and 1.13.2 support) is published now.
