### ISSUE TITLE
1.13 Issue (Regardless of Version)

### ISSUE THREAD

**Issue by CaptainAmpersand** [robingrether/iDisguise#25]
All dev builds I've tested break Scoreboards.
Spigot, PaperSpigot, Waterfall, all 1.13. Won't give an error.

After going one-by-one for 50 plugins, it was narrowed down to your dev builds.
I love this plugin, just need this fixed before the first PR :P

**Comment by luisagrether** [comment]
What exactly does "break Scoreboards" mean to you? What is broken?

**Comment by luisagrether** [comment]
And you mention "dev builds" especially. Does this mean that the problem did not occur with previous releases of iDisguise?

**Comment by CaptainAmpersand** [comment]
Scoreboards, such as Featherboard. The mcmmo notification about ranking up. The premiumvanish scoreboard letting you know you’re vanished.

IDisguise broke all of those scoreboards

**Comment by CaptainAmpersand** [comment]
It didn’t occur when I was on 1.12.2. Only dev builds successfully work on 1.13, after all :P

**Comment by luisagrether** [comment]
Ok, that already narrows the issue down to any changes from 5.7.3 to the latest dev builds. However, as Featherboard is premium, I need even more information to figure out what's the cause of the problem:
1) Do you use ProtocolLib?
2) Did you enable "disguise.modify-scoreboard-packets" in the plugin configuration?

**Comment by CaptainAmpersand** [comment]
ProtocolLib ver 4.4.0 (whatever the latest one is, even the most latest version), since I was trying to troubleshoot my scoreboard issue and assumed it was an outdated plugin

I used iDisguise out-of-the-box and didn’t change any part of the config. So, if it’s enabled by default, yes.

**Comment by robingrether** [comment]
It is enabled by default.

Would you mind testing the latest dev build with "disguise.modify-scoreboard-packets" disabled?

**Comment by luisagrether** [comment]
Would you mind trying out [iDisguise 5.8.1-SNAPSHOT \#60](http://repo.robingrether.de/de/robingrether/idisguise/idisguise-full/5.8.1-SNAPSHOT/idisguise-full-5.8.1-20181019.142604-60.jar)?
