### ISSUE TITLE
Skin Layers Missing

### ISSUE THREAD

**Issue by Boastful1353** [robingrether/iDisguise#28]
Disguising as a player doesn't pull the outer layer of the players skin.

im using 5.8.1  on spigot 1.13.2

**Comment by luisagrether** [comment]
This issue is already fixed: [iDisguise 5.8.2-SNAPSHOT \#1](http://repo.robingrether.de/de/robingrether/idisguise/idisguise-full/5.8.2-SNAPSHOT/idisguise-full-5.8.2-20181028.161826-1.jar)

**Comment by luisagrether** [comment]
I close this issue now that iDisguise 5.8.2 is officially released.
