### ISSUE TITLE
Disguised players are invulnerable

### ISSUE THREAD

**Issue by Wani4ka** [robingrether/iDisguise#31]
Disguised players don't get any damage at all.
Using 5.8.2 version on Paper 1.12.
Using additions: GadgetsMenu, iDisguiseAdditions.

**Comment by luisagrether** [comment]
I guess you set _"disable.mob-damage"_ to _true_ in the iDisguiseAdditions config file.

**Comment by Wani4ka** [comment]
Well it looks like GadgetsMenu was preventing disguised players from taking damage. I set "disable.mob-damage" to true and now players who are disguised using iDisguise take damage, while players who are disguised using GadgetsMenu do not. Thank you for your help!
