### ISSUE TITLE
iDisguise lagging my server

### ISSUE THREAD

**Issue by Fonzee9** [robingrether/iDisguise#4]
iDisguise::Command: iDisguise:disguisecount(1) total(52.60% 2.097s, 279.55% of tick)  avg(2,096.61ms per - 139.77ms/0.07 per tick)

Timings: https://timings.aikar.co/v2/?id=0321a99eaaf8453697ea01b03e06d8db&section=lag

I went to Lag tree view and then clicked Minecraft Scheduler and iDisguise was first..

**Comment by luisagrether** [comment]
Disguise as a player causes this issue: Whenever a user attempts to disguise as a player, the player's skin (and some more information) is loaded from a Mojang server. This causes some lag, as it is done synchronously.

I will fix this lag in an update quite soon.

**Comment by luisagrether** [comment]
An update which fixes the lag is available now. Download it over here: https://www.spigotmc.org/resources/idisguise.5509/
