### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ghost** [robingrether/iDisguise#7]
Hey :)
I just updated iDisguise to the latest version in my 1.8.8 offline server.
But I have this error : 
https://hastebin.com/ficurohifi.swift

Thanks and sorry for my bad english ! :)

**Comment by luisagrether** [comment]
Even though I labelled this issue as a _bug_, this is in fact not a real bug but just some needless error log. It doesn't affect gameplay at all, so you can completely ignore it until it will disappear in the next update :)

**Comment by luisagrether** [comment]
For now you can go and grab the latest snapshot of iDisguise from over here: https://www.robingrether.de/idisguise/

The error is gone in that snapshot.

**Comment by luisagrether** [comment]
Finally, you may switch to the official release (5.6.4) which contains the fix as well.

https://www.spigotmc.org/resources/idisguise.5509/
