### ISSUE TITLE
Large lag spikes when scoreboards update

### ISSUE THREAD

**Issue by basicmark** [robingrether/iDisguise#8]
We've been suffering some quite large lag spikes lasting a couple of seconds very regularly and after I did some digging I think this is due to the scoreboard packet handling and specifically the use of of Bukkit.getOfflinePlayer(String) which the bukkit documentation states is makes blocking http requests:

https://github.com/robingrether/iDisguise/blob/d5f4054a99cc80f0c01b743ceaf00db610790fce/idisguise-core/src/main/java/de/robingrether/idisguise/management/PacketHandler.java#L264

You can find the timings report at https://www.spigotmc.org/go/timings?url=qocimobiho which shows that mcMMO scoreboard update is taking 1.9 seconds on average. Looking at the detail with VisualVM it shows that its the iDisguise packet injection which is causing the issue:
![mcmmo-lag-spike](https://user-images.githubusercontent.com/652659/27264259-8c236a4a-5472-11e7-848a-6f29a9d4c4d2.png)

About 10% of the main server thread is spent in this call even though the event which calls it it very rare.

Disabling you plugin temperately seems to have resolved the issue for now but of course we would like to re-enable it :).

**Comment by luisagrether** [comment]
I had to use that blocking function since Mojang for some reason, that I cannot understand at all, decided to use player names instead of profile UIDs in those scoreboard packets. And other people have been complaining about my plugin messing up scoreboard based plugins such as health displays and player prefixes.

However, I will add a config option to disable any scoreboard modifications in the next update. I'll send you another message as soon as I upload a snapshot including this feature :)

**Comment by luisagrether** [comment]
After some thoughts I decided not to include such an option. However, the lag is fixed now. Until the next update is officially released, you can go and grab a snapshot version (#4 includes the fix) from over here: https://www.robingrether.de/idisguise/

**Comment by basicmark** [comment]
Many thanks for the quick response and bug fix, I'll push it to our server and get back to you in the next day or two just to confirm the issue has been resolved.

**Comment by luisagrether** [comment]
I'm so sorry. I accidentally put the wrong link on the website. What you downloaded was not the whole plugin but just the core part which is completely unable to run alone. Just go and download the snapshot #4 once again. I fixed the link in the mean time https://www.robingrether.de/idisguise/

**Comment by basicmark** [comment]
No worries, I thought it contained just the 1.12 and we are on 1.11.2 so I checked it out and built it locally.

It looks like the issue as been resolved, at least as far as I can see from my testing and timings report. There have been reports of lag on the server, but the symptoms seem different (I still need to investigate it) from what I've been told so I'll close this ticket.

Thanks again for the quick response on this, our players are very happy to get their disguises back :).
